# Generated by Django 3.2.4 on 2021-06-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210603_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=30)),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('default_account', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch_code', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanType', models.CharField(max_length=30)),
                ('loan_rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('branch', models.ManyToManyField(to='app1.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('aadhar_number', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ManyToManyField(to='app1.User'),
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ManyToManyField(to='app1.Branch'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ManyToManyField(to='app1.User'),
        ),
    ]
