# Generated by Django 3.2.4 on 2021-06-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210603_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_number',
            field=models.IntegerField(null=True),
        ),
    ]
